name: CMake Build

on:
  release:
    types: [published]
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VERSION_NAME: ${{ github.event.release.tag_name }}

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 6.3.0
        target: desktop

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -DCMAKE_BUILD_TYPE=Release . -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}
      run: ninja

    - name: Deploy
      working-directory: ${{github.workspace}}
      run: macdeployqt 'expunge.app' -dmg

    - name: Rename
      working-directory: ${{github.workspace}}
      run: mv 'expunge.dmg' "expunge-$VERSION_NAME-macos.dmg"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{github.workspace}}/expunge-${{github.event.release.tag_name}}-macos.dmg
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 6.3.0
        target: desktop
        arch: win64_msvc2019_64
    
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    
    - name: Setup VS Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=Release . -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}
      run: ninja

    - name: Rename
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        mkdir "expunge-$VERSION_NAME"
        mv "expunge.exe" "expunge-$VERSION_NAME/expunge.exe"
        mv "wit" "expunge-$VERSION_NAME/wit"

    - name: Deploy
      working-directory: ${{github.workspace}}
      shell: bash
      run: windeployqt "expunge-$VERSION_NAME/expunge.exe"

    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: ${{github.workspace}}
        filename: expunge-${{github.event.release.tag_name}}-windows.zip
        path: ./expunge-${{github.event.release.tag_name}}/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/expunge-${{github.event.release.tag_name}}-windows.zip
